### ISSUE TITLE
Turn riskyr into a package?

### ISSUE THREAD

**Issue by ndphillips** [hneth/riskyr#1]
Hey Hans, I see you're still hard at work on riskyr, that's great!

I was just looking at the repository and wanted to suggest that you restructure the project as an R package. Wickham has a great tutorial here [http://r-pkgs.had.co.nz/](http://r-pkgs.had.co.nz/) on creating R packages, and here's one on how to include Shiny apps [https://deanattali.com/2015/04/21/r-package-shiny-app/](https://deanattali.com/2015/04/21/r-package-shiny-app/)

I'd be happy to try and do it myself, but I really have to finish other things this month as you might have guessed :)

**Comment by hneth** [comment]
Hi Nathaniel,
good points — thanks!  Alas, I'm only so diligently updating stuff as this is the one thing I can do while on family visits between Xmas and New Years.

At the moment, I'm just dumping various snippets of existing code into a working Shiny app, but it's already clear that a more consistent and modular structure will be beneficial later.  As turning all into an R package was one of our original motivations, I look forward to tackling this part eventually — hopefully soon. (btw: Do you think you'll find time to add your existing icon array code to the app?  If not, Nico may also have some code he could use...)

I also haven't forgotten about our other projects, but as I can only sneak in short stretches of time for work these days, coding small bits is all I can do.  But this will change soon, fingers crossed.

**Comment by ndphillips** [comment]
sure thing! Sadly I haven't had any time to work on the icon array code. Too busy with finishing up Peeks and Keeps. But feel free to nudge me again :)
