### ISSUE TITLE
Include vignettes and package loading message with link to main package guide

### ISSUE THREAD

**Issue by ndphillips** [hneth/riskyr#5]
Hey guys, it looks like you guys have made tremendous progress on riskyr! I just installed it in the hopes of playing around, but without a package guide I wasn't sure how to proceed.

Do you guys plan to create one soon? It looks like you have plenty of existing documentation on GitHub, so it probably wouldn't be difficult to port it over to your package.

See my FFTrees package guide for an example: https://github.com/ndphillips/FFTrees/blob/master/vignettes/guide.Rmd

Looking forward to playing around with riskyr!!

**Comment by hneth** [comment]
Hi Nathaniel,
you're right, of course.  We now added a set of initial vignettes.  They still can be tweaked and improved in many places, but should make the package more usable, hopefully.  So feel free to give it a test drive soon...
Best,
Hans
